[package]
name = "mupen64plus-input-gca"
version = "0.1.0"
authors = ["Amandus Søve Thorsrud <ama.thorsrud@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[build-dependencies]
bindgen = "0.57.0"

[dependencies]
libloading = "0.6.2"
rusb = "0.6.2"
once_cell = "1.4.0"
